### ISSUE TITLE
side-table

### ISSUE THREAD

**Issue by mbbill** [titzer/wizard-engine#157]
Found this project through the Youtube video "[OOPSLA] A Fast In-Place Interpreter for WebAssembly" and just realized that the idea of the side-table is pretty much the same as what I have implemented in my wasm in-place interpreter project back in 2022 (https://github.com/mbbill/Silverfir/blob/main/docs/Interpreter.md)
I wrote it mostly for embedded projects because an in-place interpreter is critical for memory usage. Would love to discuss more if you don't mind.
Sorry for posting here since it's not actually an issue.

**Comment by titzer** [comment]
No worries. Looks like we had very similar ideas. One complication is the handling of branching to labels with that have values, which is why Wizard's side table has a `popcount` and a `valcount` in each entry. Those are needed for `br`s but not for `if` and `else`. Currently Wizard only uses the side-table for control, but there are good reasons to use it for some other instructions as well.
